version: '3.8'

services:
  mongodb:
    image: mongo:5.0.5
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:/data/db
    restart: unless-stopped
    ports:
      - '27017:27017'
  app:
    depends_on:
      - mongodb
    build:
      context: ./
      target: 'development'
    env_file: ./.env
    volumes:
      - ./:/app
    restart: unless-stopped

volumes:
  db: {}
